name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18.1
          cache: true
      - name: Build binary
        run: go build -ldflags "-s -w" -o build/
      - uses: actions/upload-artifact@v3
        with:
          name: Check Traefik ${{ matrix.os }}
          path: build/