name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    env:
      GOPROXY: https://proxy.golang.org
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Start test stack
        run: docker-compose -f .github/workflows/compose.yml -p test-stack up -d
      - uses: actions/cache@v3
        if: runner.os == 'Linux'
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/cache@v3
        if: runner.os == 'Windows'
        with:
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/cache@v3
        if: runner.os == 'macOS'
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18.1
      - name: Test
        run: go test -v ./...
      - name: Build binary
        run: go build -ldflags "-s -w" -o build/
      - name: Run against test stack
        run: ./build/check_traefik health -I 127.0.0.1 -H traefik.server.tld --url /monitoring/ping --username monitoring --password password --ssl --insecure
      - uses: actions/upload-artifact@v3
        with:
          name: Check Traefik ${{ matrix.os }}
          path: build/
      - name: Stop test stack
        if: always()
        run: docker-compose -f .github/workflows/compose.yml -p test-stack down
